[package]
name = "rocket-recaptcha-v3"
version = "0.2.4"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2018"
repository = "https://github.com/magiclen/rocket-recaptcha-v3"
homepage = "https://magiclen.org/rocket-recaptcha-v3"
keywords = ["rocket", "reCAPTCHA", "google", "captcha"]
categories = ["web-programming"]
description= "This crate can help you use reCAPTCHA v3 (v2 is backward compatible) in your Rocket web application."
readme = "README.md"
license = "MIT"
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]

[badges.travis-ci]
repository = "magiclen/rocket-recaptcha-v3"
branch = "master"

[dependencies]
rocket = "0.4.2"
once_cell = "1"
easy-http-request = "0.2"
serde = "1"
serde_derive = "1"
serde_json = "1"
chrono = "0.4"
validators = "0.22"

rocket-client-addr = "0.4"

[dependencies.validators-derive]
version = "0.22"
default-features = false
features = ["rocket", "base64_url", "regex"]

[dev-dependencies]
rocket-include-tera = "0.4"