[package]
name = "rocket-recaptcha-v3"
version = "0.3.0"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2018"
repository = "https://github.com/magiclen/rocket-recaptcha-v3"
homepage = "https://magiclen.org/rocket-recaptcha-v3"
keywords = ["rocket", "reCAPTCHA", "google", "captcha"]
categories = ["web-programming"]
description = "This crate can help you use reCAPTCHA v3 (v2 is backward compatible) in your Rocket web application."
readme = "README.md"
license = "MIT"
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]

[badges.travis-ci]
repository = "magiclen/rocket-recaptcha-v3"
branch = "master"

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket", version = "0.5.0-dev" }
once_cell = "1"
reqwest = "0.11"
serde = "1"
serde_derive = "1"
serde_json = "1"
chrono = "0.4"
validators = { git = "https://github.com/magiclen/validators", version = "0.23" }

rocket-client-addr = { git = "https://github.com/magiclen/rocket-client-addr", version = "0.5" }

[dependencies.validators-derive]
version = "0.23"
git = "https://github.com/magiclen/validators"
default-features = false
features = ["rocket", "base64_url", "regex"]

[dev-dependencies]
rocket-include-tera = { git = "https://github.com/magiclen/rocket-include-tera", version = "0.5" }